run:
  concurrency: 4
  timeout: 5m
  allow-parallel-runners: true
  allow-serial-runners: true
  print-resources-usage: true
  go: '1.22'
linters:
  enable:
    - gofmt
    - gosec
    - misspell
    - whitespace
    - zerologlint
