version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: build

  build:
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-w" -v -o ./bin/gogl ./cmd/cli

  test:
    cmds:
      - go test -v ./... -coverprofile=coverage.out
      - |
        go tool cover -func coverage.out | tail -n 1 | awk '{ print "Total coverage: " $3 }'

  install:
    cmds:
      - task: build
      - cp ./bin/gogl ~/.local/bin/gogl

