version: '3'

tasks:
  default:
    cmds:
      - task: test
      - task: build

  lint:
    cmds:
      - gofmt -w .
      - golangci-lint run

  build:
    cmds:
      - CGO_ENABLED=0 go build -ldflags "-w" -v -o ./bin/gogl ./cmd/cli

  docker:
    cmds:
      - docker buildx build --output "type=docker,push=false" --tag ghcr.io/watcherwhale/gogl:dev .

  docker-publish:
    cmds:
      - docker buildx build --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x --tag ghcr.io/watcherwhale/gogl:dev --push .

  test:
    cmds:
      - go test -v ./... -coverprofile=coverage.out
      - |
        go tool cover -func coverage.out | tail -n 1 | awk '{ print "Total coverage: " $3 }'

  install:
    cmds:
      - task: build
      - cp ./bin/gogl ~/.local/bin/gogl

