// Code generated by 'yaegi extract github.com/watcherwhale/gogl-ci/pkg/graph'. DO NOT EDIT.

package symbols

import (
	"github.com/watcherwhale/gogl-ci/pkg/graph"
	"reflect"
)

func init() {
	Symbols["github.com/watcherwhale/gogl-ci/pkg/graph/graph"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewGraph": reflect.ValueOf(graph.NewGraph),

		// type definitions
		"JobGraph": reflect.ValueOf((*graph.JobGraph)(nil)),
	}
}
